name: timeless
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.3.0
  common_utils: ^2.0.2


executables:
  timeless: 
